name: SmartRangeFinder Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  srf-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run SmartRangeFinder integration test
        # Run the test module in isolation to avoid pytest runner issues
        run: |
          python -c "import runpy; runpy.run_path('tests/test_smart_range_finder_integration.py', run_name='__main__')"

      - name: Upload SRF analysis artifact
        uses: actions/upload-artifact@v4
        with:
          name: srf-analysis-${{ github.run_id }}
          path: |
            tests/tmp_range_analysis.json
