name: Run tests (pytest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    name: Run tests (pytest matrix with Postgres)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/testdb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres -d testdb && break || sleep 2
          done

      - name: Run alembic migrations
        run: |
          alembic upgrade head

      - name: Show Alembic current
        run: |
          alembic current

      - name: Seed sample data with CLI
        if: github.ref == 'refs/heads/main'
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          # retry up to 3 times in case Postgres is still finishing startup
          attempts=0
          max_attempts=3
          until [ $attempts -ge $max_attempts ]
          do
            attempts=$((attempts+1))
            echo "Seed attempt $attempts/$max_attempts"
            python -m src.cli seed-db --csv scripts/sample_candles.csv && break || true
            echo "Seed failed, sleeping 5s before retry"
            sleep 5
          done

      - name: Verify seeded symbols
        if: github.ref == 'refs/heads/main'
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          python -m src.cli list-symbols

      - name: Check symbol count
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          count=$(python -m src.cli list-symbols | wc -l)
          echo "Seeded symbols: $count"
          if [ "$count" -eq 0 ]; then
            echo "❌ No symbols seeded!"
            exit 1
          fi

      - name: Run pytest
        run: |
          pytest -q --maxfail=1 --disable-warnings -v
        env:
          PYTHONUNBUFFERED: '1'

